language: python

python:
  - "2.7"

sudo: false

virtualenv:
  system_site_packages: true

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/local
    - $HOME/localpy

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kubuntu-backports
      - couchbase-precise
    packages:
      - python-scipy
      - python-numpy
#      - python-h5py

before_install:
  - echo $HOME
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/local/lib:${HOME}/local/lib64
  - export PYTHONPATH=${HOME}/localpy:${PYTHONPATH}
install:
# Install nutcracker
  - cd $HOME/build/FXIhub/nutcracker
  - python setup.py install
# command to run tests
script:
  - echo $LD_LIBRARY_PATH
  - echo $PYTHONPATH
  # TESTING IMPORTS
  - python -c "import condor; print condor.__file__"
  # UNITTESTS
  - python -m unittest -v nutcracker.tests.test_all
  # EXAMPLES
