language: python

python:
  - "2.7"

sudo: false

virtualenv:
  system_site_packages: true

#cache:
#  directories:
#    - $HOME/.cache/pip
#    - $HOME/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared
#    - $HOME/nfft-3.2.3
#    - $HOME/libspimage
#    - $HOME/spsim
#    - $HOME/local
#    - $HOME/localpy
    
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kubuntu-backports
      - couchbase-precise
    packages:
      - libpng-dev
      - libtiff4-dev
      - libfftw3-dev
      - cmake
      - gsl-bin
      - libgsl0-dev
      - swig
 # Python stuff (for discovering these packages set in virtualenv: system_site_packages: true)
      - python-scipy
      - python-numpy
#      - python-h5py

before_install:
  - echo $HOME
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/local/lib:${HOME}/local/lib64
  - export PYTHONPATH=${HOME}/localpy:${PYTHONPATH}
# Install hdf5
  - cd $HOME
  - if [ ! -d "$HOME/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/include" ]; then wget https://support.hdfgroup.org/ftp/HDF5/current/bin/linux-centos7-x86_64-gcc485/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared.tar.gz && tar xvzf hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared.tar.gz; else echo 'Using hdf5 from cached directory'; fi
  - export LD_LIBRARY_PATH=${HOME}/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/lib:${LD_LIBRARY_PATH}
  - ls ${HOME}/
  - ls ${HOME}/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/
  - ls ${HOME}/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/lib
  - ls ${HOME}/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/lib
# Install libspimage
  - cd $HOME
  - if [ ! -d "$HOME/libspimage/.git" ]; then git clone https://github.com/FilipeMaia/libspimage; else echo 'Using libspimage from cached directory'; fi
  - mkdir -p libspimage/build && cd libspimage/build
  - git pull
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DUSE_CUDA=OFF -DPYTHON_WRAPPERS=ON -DHDF5_INCLUDE_DIR=$HOME/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/include -DHDF5_LIBRARY=$HOME/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/lib/libhdf5.so -DCMAKE_INSTALL_PREFIX=${HOME}/local -DPYTHON_INSTDIR=${HOME}/localpy -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_INCLUDE_DIR2=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so ..
  - make -j 2 VERBOSE=1
  - make install
# Install NFFT
  - cd $HOME
  - if [ ! -d "$HOME/nfft-3.2.3/include" ]; then wget https://www-user.tu-chemnitz.de/~potts/nfft/download/nfft-3.2.3.tar.gz && tar xvzf nfft-3.2.3.tar.gz; cd nfft-3.2.3 && ./configure --prefix=${HOME}/local && make && make install; else echo 'Using NFFT from cached directory'; fi
# Install spsim
  - cd $HOME
  - if [ ! -d "$HOME/spsim/.git" ]; then git clone https://github.com/FilipeMaia/spsim; else echo 'Using spsim from cached directory'; fi
  - mkdir -p spsim/build && cd spsim/build
  - git pull
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_LIBRARY=ON -DUSE_CUDA=OFF -DUSE_NFFT=OFF -DPYTHON_WRAPPERS=ON -DHDF5_INCLUDE_DIR=$HOME/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/include -DHDF5_LIBRARY=$HOME/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/lib/libhdf5.so -DCMAKE_INSTALL_PREFIX=${HOME}/local -DPYTHON_INSTDIR=${HOME}/localpy -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so -DPYTHON_INCLUDE_DIR2=/usr/include/python2.7 ..
  - make -j 2 VERBOSE=1
  - make install
  - ls -alh $HOME/local/lib
  - ls -alh /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
  - ls -alh /home/travis/virtualenv/python2.7_with_system_site_packages/lib/python2.7/site-packages
# install condor
  - cd $HOME
  - if [ ! -d "$HOME/condor/.git" ]; then git clone https://github.com/FXIhub/condor; else echo 'Using condor from cached directory'; fi
  - cd $HOME/condor
  - git pull
install:
# Install h5py (we want an h5py that is built with the new hdf5 version, that is why)
  - export HDF5_DIR=${HOME}/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/
  - pip install h5py
# Install condor
  - cd $HOME/condor
  - python setup.py install --nfft-include-dir=$HOME/local/include --nfft-library-dir=$HOME/local/lib
# Install nutcracker
  - cd $HOME/build/FXIhub/nutcracker
  - python setup.py install
# command to run tests
script:
  - echo $LD_LIBRARY_PATH
  - echo $PYTHONPATH
  # TESTING IMPORTS
#  - python -c "import condor; print condor.__file__"
  # UNITTESTS
  - python -m unittest -v nutcracker.tests.test_all
  # EXAMPLES
